name: Compile the paper
on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Setup Typst
        uses: typst-community/setup-typst@v4.3.0
      - name: Compile main.typ
        run: typst compile paper/main.typ paper.pdf
      - name: Upload compiled paper
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
